// Generated from AccuracyCoin.asm — do not edit by hand.
//
// AccuracyCoin is MIT-licensed, © 2025 Chris Siebert
// (https://github.com/100thCoin/AccuracyCoin). This table is the test names and
// result addresses read out of the ROM's own `TestPages:` table and the
// `result_*` equates beside it, which is fact about the ROM's memory map rather
// than any of its code; it is reproduced here under the MIT licence, with
// attribution, so the runner can name what failed without the ROM present.
//
// Regenerate by re-reading `TestPages:` and the `result_* = $xxx` equates in
// AccuracyCoin.asm. The ordering is the ROM's: page by page, top to bottom, so
// a report reads the same way the on-screen menu does.
//
// The five entries with a result address on page 3 ($03FB-$03FF) are the "DRAW"
// pages, which display information rather than asserting anything. The ROM's
// own run-all loop skips them and so does the runner; they are kept here so the
// table is a complete picture of the menu.

/// Every test in the ROM, in menu order.
pub(crate) static TESTS: [Test; 130] = [
    Test { suite: "CPU Behavior",        name: "ROM is not writable",             result: 0x0405 },
    Test { suite: "CPU Behavior",        name: "RAM Mirroring",                   result: 0x0403 },
    Test { suite: "CPU Behavior",        name: "PC Wraparound",                   result: 0x044d },
    Test { suite: "CPU Behavior",        name: "The Decimal Flag",                result: 0x0474 },
    Test { suite: "CPU Behavior",        name: "The B Flag",                      result: 0x0475 },
    Test { suite: "CPU Behavior",        name: "Dummy read cycles",               result: 0x0406 },
    Test { suite: "CPU Behavior",        name: "Dummy write cycles",              result: 0x0407 },
    Test { suite: "CPU Behavior",        name: "Open Bus",                        result: 0x0408 },
    Test { suite: "CPU Behavior",        name: "Unofficial Instructions",         result: 0x0402 },
    Test { suite: "CPU Behavior",        name: "All NOP instructions",            result: 0x047d },
    Test { suite: "Addressing mode wraparound", name: "Absolute Indexed",                result: 0x046e },
    Test { suite: "Addressing mode wraparound", name: "Zero Page Indexed",               result: 0x046f },
    Test { suite: "Addressing mode wraparound", name: "Indirect",                        result: 0x0470 },
    Test { suite: "Addressing mode wraparound", name: "Indirect, X",                     result: 0x0471 },
    Test { suite: "Addressing mode wraparound", name: "Indirect, Y",                     result: 0x0472 },
    Test { suite: "Addressing mode wraparound", name: "Relative",                        result: 0x0473 },
    Test { suite: "Unofficial Instructions: SLO", name: "$03   SLO indirect,X",            result: 0x0409 },
    Test { suite: "Unofficial Instructions: SLO", name: "$07   SLO zeropage",              result: 0x040a },
    Test { suite: "Unofficial Instructions: SLO", name: "$0F   SLO absolute",              result: 0x040b },
    Test { suite: "Unofficial Instructions: SLO", name: "$13   SLO indirect,Y",            result: 0x040c },
    Test { suite: "Unofficial Instructions: SLO", name: "$17   SLO zeropage,X",            result: 0x040d },
    Test { suite: "Unofficial Instructions: SLO", name: "$1B   SLO absolute,Y",            result: 0x040e },
    Test { suite: "Unofficial Instructions: SLO", name: "$1F   SLO absolute,X",            result: 0x040f },
    Test { suite: "Unofficial Instructions: RLA", name: "$23   RLA indirect,X",            result: 0x0419 },
    Test { suite: "Unofficial Instructions: RLA", name: "$27   RLA zeropage",              result: 0x041a },
    Test { suite: "Unofficial Instructions: RLA", name: "$2F   RLA absolute",              result: 0x041b },
    Test { suite: "Unofficial Instructions: RLA", name: "$33   RLA indirect,Y",            result: 0x041c },
    Test { suite: "Unofficial Instructions: RLA", name: "$37   RLA zeropage,X",            result: 0x041d },
    Test { suite: "Unofficial Instructions: RLA", name: "$3B   RLA absolute,Y",            result: 0x041e },
    Test { suite: "Unofficial Instructions: RLA", name: "$3F   RLA absolute,X",            result: 0x041f },
    Test { suite: "Unofficial Instructions: SRE", name: "$43   SRE indirect,X",            result: 0x0420 },
    Test { suite: "Unofficial Instructions: SRE", name: "$47   SRE zeropage",              result: 0x047f },
    Test { suite: "Unofficial Instructions: SRE", name: "$4F   SRE absolute",              result: 0x0422 },
    Test { suite: "Unofficial Instructions: SRE", name: "$53   SRE indirect,Y",            result: 0x0423 },
    Test { suite: "Unofficial Instructions: SRE", name: "$57   SRE zeropage,X",            result: 0x0424 },
    Test { suite: "Unofficial Instructions: SRE", name: "$5B   SRE absolute,Y",            result: 0x0425 },
    Test { suite: "Unofficial Instructions: SRE", name: "$5F   SRE absolute,X",            result: 0x0426 },
    Test { suite: "Unofficial Instructions: RRA", name: "$63   RRA indirect,X",            result: 0x0427 },
    Test { suite: "Unofficial Instructions: RRA", name: "$67   RRA zeropage",              result: 0x0428 },
    Test { suite: "Unofficial Instructions: RRA", name: "$6F   RRA absolute",              result: 0x0429 },
    Test { suite: "Unofficial Instructions: RRA", name: "$73   RRA indirect,Y",            result: 0x042a },
    Test { suite: "Unofficial Instructions: RRA", name: "$77   RRA zeropage,X",            result: 0x042b },
    Test { suite: "Unofficial Instructions: RRA", name: "$7B   RRA absolute,Y",            result: 0x042c },
    Test { suite: "Unofficial Instructions: RRA", name: "$7F   RRA absolute,X",            result: 0x042d },
    Test { suite: "Unofficial Instructions: *AX", name: "$83   SAX indirect,X",            result: 0x042e },
    Test { suite: "Unofficial Instructions: *AX", name: "$87   SAX zeropage",              result: 0x042f },
    Test { suite: "Unofficial Instructions: *AX", name: "$8F   SAX absolute",              result: 0x0430 },
    Test { suite: "Unofficial Instructions: *AX", name: "$97   SAX zeropage,Y",            result: 0x0431 },
    Test { suite: "Unofficial Instructions: *AX", name: "$A3   LAX indirect,X",            result: 0x0432 },
    Test { suite: "Unofficial Instructions: *AX", name: "$A7   LAX zeropage",              result: 0x0433 },
    Test { suite: "Unofficial Instructions: *AX", name: "$AF   LAX absolute",              result: 0x0434 },
    Test { suite: "Unofficial Instructions: *AX", name: "$B3   LAX indirect,Y",            result: 0x0435 },
    Test { suite: "Unofficial Instructions: *AX", name: "$B7   LAX zeropage,X",            result: 0x0436 },
    Test { suite: "Unofficial Instructions: *AX", name: "$BF   LAX absolute,X",            result: 0x0437 },
    Test { suite: "Unofficial Instructions: DCP", name: "$C3   DCP indirect,X",            result: 0x0438 },
    Test { suite: "Unofficial Instructions: DCP", name: "$C7   DCP zeropage",              result: 0x0439 },
    Test { suite: "Unofficial Instructions: DCP", name: "$CF   DCP absolute",              result: 0x043a },
    Test { suite: "Unofficial Instructions: DCP", name: "$C3   DCP indirect,Y",            result: 0x043b },
    Test { suite: "Unofficial Instructions: DCP", name: "$B7   DCP zeropage,X",            result: 0x043c },
    Test { suite: "Unofficial Instructions: DCP", name: "$BB   DCP absolute,Y",            result: 0x043d },
    Test { suite: "Unofficial Instructions: DCP", name: "$BF   DCP absolute,X",            result: 0x043e },
    Test { suite: "Unofficial Instructions: ISC", name: "$E3   ISC indirect,X",            result: 0x043f },
    Test { suite: "Unofficial Instructions: ISC", name: "$E7   ISC zeropage",              result: 0x0440 },
    Test { suite: "Unofficial Instructions: ISC", name: "$EF   ISC absolute",              result: 0x0441 },
    Test { suite: "Unofficial Instructions: ISC", name: "$F3   ISC indirect,Y",            result: 0x0442 },
    Test { suite: "Unofficial Instructions: ISC", name: "$F7   ISC zeropage,X",            result: 0x0443 },
    Test { suite: "Unofficial Instructions: ISC", name: "$FB   ISC absolute,Y",            result: 0x0444 },
    Test { suite: "Unofficial Instructions: ISC", name: "$FF   ISC absolute,X",            result: 0x0445 },
    Test { suite: "Unofficial Instructions: SH*", name: "$93   SHA indirect,Y",            result: 0x0446 },
    Test { suite: "Unofficial Instructions: SH*", name: "$9F   SHA absolute,Y",            result: 0x0447 },
    Test { suite: "Unofficial Instructions: SH*", name: "$9B   SHS absolute,Y",            result: 0x0448 },
    Test { suite: "Unofficial Instructions: SH*", name: "$9C   SHY absolute,X",            result: 0x0449 },
    Test { suite: "Unofficial Instructions: SH*", name: "$9E   SHX absolute,Y",            result: 0x044a },
    Test { suite: "Unofficial Instructions: SH*", name: "$BB   LAE absolute,Y",            result: 0x044b },
    Test { suite: "Unofficial Immediates", name: "$0B   ANC Immediate",             result: 0x0410 },
    Test { suite: "Unofficial Immediates", name: "$2B   ANC Immediate",             result: 0x0411 },
    Test { suite: "Unofficial Immediates", name: "$4B   ASR Immediate",             result: 0x0412 },
    Test { suite: "Unofficial Immediates", name: "$6B   ARR Immediate",             result: 0x0413 },
    Test { suite: "Unofficial Immediates", name: "$8B   ANE Immediate",             result: 0x0414 },
    Test { suite: "Unofficial Immediates", name: "$AB   LXA Immediate",             result: 0x0415 },
    Test { suite: "Unofficial Immediates", name: "$CB   AXS Immediate",             result: 0x0416 },
    Test { suite: "Unofficial Immediates", name: "$EB   SBC Immediate",             result: 0x0417 },
    Test { suite: "Unofficial Immediates", name: "Print magic values",              result: 0x03fb },
    Test { suite: "CPU Interrupts",      name: "Interrupt flag latency",          result: 0x0461 },
    Test { suite: "CPU Interrupts",      name: "NMI Overlap BRK",                 result: 0x0462 },
    Test { suite: "CPU Interrupts",      name: "NMI Overlap IRQ",                 result: 0x0463 },
    Test { suite: "APU Registers and DMA tests", name: "DMA + Open Bus",                  result: 0x046c },
    Test { suite: "APU Registers and DMA tests", name: "DMA + $2007 Read",                result: 0x044c },
    Test { suite: "APU Registers and DMA tests", name: "DMA + $2007 Write",               result: 0x044f },
    Test { suite: "APU Registers and DMA tests", name: "DMA + $4015 Read",                result: 0x045d },
    Test { suite: "APU Registers and DMA tests", name: "DMA + $4016 Read",                result: 0x045e },
    Test { suite: "APU Registers and DMA tests", name: "APU Register Activation",         result: 0x045c },
    Test { suite: "APU Registers and DMA tests", name: "DMC DMA Bus Conflicts",           result: 0x046b },
    Test { suite: "APU Registers and DMA tests", name: "DMC DMA + OAM DMA",               result: 0x0477 },
    Test { suite: "APU Registers and DMA tests", name: "Explicit DMA Abort",              result: 0x0479 },
    Test { suite: "APU Registers and DMA tests", name: "Implicit DMA Abort",              result: 0x0478 },
    Test { suite: "APU Timing",          name: "Length Counter",                  result: 0x0465 },
    Test { suite: "APU Timing",          name: "Length Table",                    result: 0x0466 },
    Test { suite: "APU Timing",          name: "Frame Counter IRQ",               result: 0x0467 },
    Test { suite: "APU Timing",          name: "Frame Counter 4-step",            result: 0x0468 },
    Test { suite: "APU Timing",          name: "Frame Counter 5-step",            result: 0x0469 },
    Test { suite: "APU Timing",          name: "Delta Modulation Channel",        result: 0x046a },
    Test { suite: "APU Timing",          name: "Controller Strobing",             result: 0x045f },
    Test { suite: "APU Timing",          name: "Controller Clocking",             result: 0x047a },
    Test { suite: "Power On State",      name: "PPU Reset Flag",                  result: 0x0418 },
    Test { suite: "Power On State",      name: "CPU RAM",                         result: 0x03fc },
    Test { suite: "Power On State",      name: "CPU Registers",                   result: 0x03fd },
    Test { suite: "Power On State",      name: "PPU RAM",                         result: 0x03fe },
    Test { suite: "Power On State",      name: "Palette RAM",                     result: 0x03ff },
    Test { suite: "PPU Behavior",        name: "PPU Register Mirroring",          result: 0x0404 },
    Test { suite: "PPU Behavior",        name: "PPU Register Open Bus",           result: 0x044e },
    Test { suite: "PPU Behavior",        name: "PPU Read Buffer",                 result: 0x0476 },
    Test { suite: "PPU Behavior",        name: "Palette RAM Quirks",              result: 0x047e },
    Test { suite: "PPU VBlank Timing",   name: "VBlank beginning",                result: 0x0450 },
    Test { suite: "PPU VBlank Timing",   name: "VBlank end",                      result: 0x0451 },
    Test { suite: "PPU VBlank Timing",   name: "NMI Control",                     result: 0x0452 },
    Test { suite: "PPU VBlank Timing",   name: "NMI Timing",                      result: 0x0453 },
    Test { suite: "PPU VBlank Timing",   name: "NMI Suppression",                 result: 0x0454 },
    Test { suite: "PPU VBlank Timing",   name: "NMI at VBlank end",               result: 0x0455 },
    Test { suite: "PPU VBlank Timing",   name: "NMI disabled at VBlank",          result: 0x0456 },
    Test { suite: "Sprite Evaluation",   name: "Sprite overflow behavior",        result: 0x0459 },
    Test { suite: "Sprite Evaluation",   name: "Sprite 0 Hit behavior",           result: 0x0457 },
    Test { suite: "Sprite Evaluation",   name: "Arbitrary Sprite zero",           result: 0x0458 },
    Test { suite: "Sprite Evaluation",   name: "Misaligned OAM behavior",         result: 0x045a },
    Test { suite: "Sprite Evaluation",   name: "Address $2004 behavior",          result: 0x045b },
    Test { suite: "Sprite Evaluation",   name: "OAM Corruption",                  result: 0x047b },
    Test { suite: "PPU Misc.",           name: "RMW $2007 Extra Write",           result: 0x0464 },
    Test { suite: "CPU Behavior 2",      name: "Instruction Timing",              result: 0x0460 },
    Test { suite: "CPU Behavior 2",      name: "Implied Dummy Reads",             result: 0x046d },
    Test { suite: "CPU Behavior 2",      name: "JSR Edge Cases",                  result: 0x047c },
];
