//! A save state written on one host, loaded on another — and both machines run
//! forward (`ROADMAP.md` §4.5, phase 9's gate).
//!
//! `tests/record_replay.rs` pins a *recording* and its resulting state hash as
//! constants, so replaying them under a second target is the whole cross-host
//! test for the record/replay seam. The snapshot seam had no equivalent: every
//! snapshot test in the tree saves and loads inside one process on one host, so
//! a host that disagreed with every other host would pass all of them as long
//! as it disagreed with itself consistently. What crossed a host boundary was
//! *replay*. What did not was a **save state** — which is the artefact with
//! users on it, since `rsemu_save`/`rsemu_load` are a button in
//! `web/src/session.js`.
//!
//! This file is the missing half, and it is deliberately not shaped like the
//! recording test.
//!
//! # Why an artefact on disk rather than a constant in the source
//!
//! A recording of a person typing at an Apple 1 is 40 bytes. A snapshot of the
//! same machine is its whole RAM, and a constant that large is unreadable, is
//! rewritten by every unrelated change to any board on the list, and — the
//! fatal part — would have to be regenerated by the same author who is
//! asserting it is right. So the artefact is written by one process and read by
//! another: `scripts/check.sh crosshost` runs the writer under a second target
//! and the reader natively, and the bytes travel through a directory.
//!
//! With neither environment variable set the reader produces the artefacts
//! itself, so an ordinary `cargo test` still runs the whole shape on one host.
//! That run proves the *load path*; only the two-process run proves the **host
//! boundary**, and only that one asserts
//! `a_foreign_snapshot_is_byte_identical_to_this_hosts_own`.
//!
//! # Why both machines run forward
//!
//! `save -> load -> save` byte equality and
//! [`Machine::state_hash`](rsemu::machine::Machine::state_hash) are both
//! functions of the fields `save` **writes**. A field `save` omits cannot make
//! either fail, however wrong the restored machine is — that is how a lost
//! sub-tick clock phase survived every snapshot test in this tree until
//! `tests/smp_snapshot.rs` ran two machines on. So the writer records *two*
//! artefacts per board: the snapshot at the instant it was taken, and the
//! snapshot of the same machine after it has run on for another span. The
//! reader loads the first into a board that has only ever been reset, runs it
//! the same span, and must produce the second. State the writer's host kept and
//! this one did not shows up there and nowhere else.
//!
//! # The boards
//!
//! [`boards`] is every shipped board whose media are either a demo image this
//! crate already publishes or a handful of inline bytes, and whose RAM is small
//! enough to send through a file. That is eight guest architectures between
//! them — 6502, Z80, 68000, MIPS, ARM (A-profile, M-profile and A64) and RISC-V
//! — plus a PPU, a framebuffer, an SPI NOR part and an I²C EEPROM.
//!
//! It is not the whole catalog. `src/machine/catalog.rs`'s
//! `every_shipped_machine_resumes_from_its_own_snapshot` is, and it runs under
//! `wasm32-wasip1` too (`scripts/check.sh crosshost`), which covers the boards
//! left out here for everything except byte-identity with a native host.
//!
//! # What this cannot prove
//!
//! No board on the list has a **drive**, and that is not an oversight: a medium
//! snapshotted by reference (`dev::medium::Snapshot::Reference`, which is what
//! any file-backed image defaults to) writes a canonical *host path* into its
//! chunk, so it cannot cross a host boundary by construction and could not be
//! made to by anything in this file. `a_snapshot_carries_no_host_path` is the
//! audit that keeps the two camps apart, and it is expected to fail the day a
//! board here gets a referenced drive — that failure is the finding.
//!
//! Nor is a **big-endian** host proved: none is buildable-and-runnable here.
//! `MIPS` and `m68k` are big-endian *guests* on a little-endian host, which
//! tests the guest side of `core::value::Endian` and says nothing about the
//! host side.

#![cfg(all(feature = "std", feature = "machine-apple1"))]

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use rsemu::core::clock::GlobalTime;
use rsemu::machine::{Machine, catalog};

/// Where the writer puts its files. Set by `scripts/check.sh crosshost`.
const WRITE_DIR: &str = "RSEMU_SNAPSHOT_WRITE_DIR";

/// Where the reader looks for them. Unset in an ordinary `cargo test`, which
/// then makes its own and checks the same-host half of the claim.
const READ_DIR: &str = "RSEMU_SNAPSHOT_READ_DIR";

/// How far a board runs before the snapshot. Long enough that every core on
/// the list has executed thousands of instructions and its timers have fired,
/// short enough that eleven boards is still a fast test.
const SPAN_A: GlobalTime = GlobalTime::from_nanos(20_000_000);

/// How far both machines run after the restore.
const SPAN_B: GlobalTime = GlobalTime::from_nanos(20_000_000);

/// A board this test can build, run and snapshot without a corpus.
struct Board {
    /// Its catalog name, which is also its artefact's file name.
    name: &'static str,
    /// What to bind to each media slot the description declares.
    media: fn() -> Vec<(&'static str, Vec<u8>)>,
    /// Parameter overrides, used only to cut a board's RAM down to something
    /// worth copying four times and sending through a file.
    params: &'static [(&'static str, &'static str)],
}

/// The boards, in catalog order.
///
/// Every entry is behind its own feature, so a build with only `machine-apple1`
/// — which is what `scripts/check.sh crosshost` builds for its second target —
/// gets a list of one and still tests the whole shape.
fn boards() -> Vec<Board> {
    let mut boards: Vec<Board> = Vec::new();

    boards.push(Board {
        name: "apple1",
        media: || vec![("rom", rsemu::dev::apple1::RSMON.to_vec())],
        params: &[],
    });

    #[cfg(feature = "machine-nes")]
    boards.push(Board {
        name: "nes-ntsc",
        media: || vec![("cart", nrom_cartridge())],
        params: &[],
    });

    #[cfg(feature = "machine-beneater")]
    boards.push(Board {
        name: "beneater-6502",
        media: || vec![("rom", rsemu::dev::wdc::RSMON_IMAGE.to_vec())],
        params: &[],
    });

    // `JR -2`, the Z80 branch-to-self: enough to prove the board realizes and
    // the core fetches, which is all a snapshot needs of it.
    #[cfg(feature = "machine-z80-mini")]
    boards.push(Board {
        name: "z80-mini",
        media: || vec![("firmware", vec![0x18, 0xfe])],
        params: &[],
    });

    // A 68000's two reset longwords — stack pointer, then program counter —
    // and `BRA .` at the address they name.
    #[cfg(feature = "machine-m68k-mini")]
    boards.push(Board {
        name: "m68k-mini",
        media: || {
            vec![(
                "firmware",
                vec![
                    0x00, 0x20, 0x00, 0x00, // SSP = $00200000
                    0x00, 0x00, 0x00, 0x08, // PC  = $00000008
                    0x60, 0xfe, // BRA .
                ],
            )]
        },
        params: &[("ram", "64K")],
    });

    // `j .` and the delay slot it drags along, since no transfer of control on
    // MIPS travels alone.
    #[cfg(feature = "machine-mips-mini")]
    boards.push(Board {
        name: "mips-mini",
        media: || {
            vec![(
                "firmware",
                vec![
                    0x00, 0x00, 0xf0, 0x0b, // j 0xbfc00000
                    0x00, 0x00, 0x00, 0x00, // nop
                ],
            )]
        },
        params: &[("ram", "64K")],
    });

    // `B .`, four bytes of A64.
    #[cfg(feature = "machine-a64-mini")]
    boards.push(Board {
        name: "a64-mini",
        media: || vec![("firmware", vec![0x00, 0x00, 0x00, 0x14])],
        params: &[("ram", "1M")],
    });

    // `B .`, four bytes of A32.
    #[cfg(feature = "machine-arm926")]
    boards.push(Board {
        name: "arm926",
        media: || vec![("firmware", vec![0xfe, 0xff, 0xff, 0xea])],
        params: &[("ram", "1M")],
    });

    // A Cortex-M4's two reset words and `B .` at the address the second names,
    // with bit 0 set because there is no ARM state to interwork to.
    #[cfg(feature = "machine-stm32f407")]
    boards.push(Board {
        name: "stm32f407",
        media: || {
            vec![(
                "firmware",
                vec![
                    0x00, 0x00, 0x02, 0x20, // SP = 0x20020000
                    0x09, 0x00, 0x00, 0x00, // PC = 0x00000008 | 1
                    0xfe, 0xe7, // b .
                ],
            )]
        },
        params: &[],
    });

    // The two boards whose demo firmware this crate assembles at compile time:
    // real drivers talking to a real part, which is a far better snapshot
    // subject than a branch-to-self.
    #[cfg(feature = "machine-spi-flash")]
    boards.push(Board {
        name: "spi-flash",
        media: || vec![("firmware", rsemu::dev::stm32::demo::SPI_FLASH_DEMO.to_vec())],
        params: &[],
    });

    #[cfg(feature = "machine-spi-panel")]
    boards.push(Board {
        name: "spi-panel",
        media: || vec![("firmware", rsemu::dev::lcd::demo::PANEL_DEMO.to_vec())],
        params: &[],
    });

    boards
}

/// The smallest NROM cartridge that resets somewhere and stays there.
///
/// Sixteen bytes of iNES header, one 16 KiB PRG bank whose reset vector points
/// at a `JMP` to itself, and one 8 KiB CHR bank of zeroes — so the PPU has
/// pattern memory to fetch and the snapshot has a PPU worth taking.
#[cfg(feature = "machine-nes")]
fn nrom_cartridge() -> Vec<u8> {
    let mut image = vec![0u8; 16 + 16 * 1024 + 8 * 1024];
    image[..4].copy_from_slice(b"NES\x1a");
    image[4] = 1; // one 16 KiB PRG bank
    image[5] = 1; // one 8 KiB CHR bank
    let prg = &mut image[16..16 + 16 * 1024];
    // $C000: JMP $C000. NROM-128 mirrors the bank at $8000 and $C000, so the
    // vectors at the top of the bank are the ones the CPU fetches.
    prg[0..3].copy_from_slice(&[0x4c, 0x00, 0xc0]);
    // NMI $C000, RESET $C000, IRQ $C000.
    prg[0x3ffa..0x4000].copy_from_slice(&[0x00, 0xc0, 0x00, 0xc0, 0x00, 0xc0]);
    image
}

/// Boards whose snapshot does not survive a restore, and why.
///
/// A known-failures ledger that only ever shrinks (`CLAUDE.md`). An entry here
/// is a defect that has been *located*, not a board that is excused, and
/// [`against_the_ledger`] fails if a listed board starts passing — so an entry
/// cannot outlive its bug.
///
/// `nes-ntsc` is here because this file found it. `apu.nes`'s `Core::save`
/// writes the frame counter, the five channels, `ticks` and `phase`, and not
/// `irq_out` — the `/IRQ` level as it stood one CPU cycle ago, which is what a
/// 6502 samples and is therefore architectural state rather than a cache. A
/// restore rebuilds it as `false` from `Core::new`, `refresh_irq` then drives
/// `apu.irq -> cpu.irq` low, and the machine's own `/wires` chunk — which
/// *does* carry the level — is overwritten by the realize sweep on the way in.
/// The guest loses a pending frame interrupt across a save state.
///
/// It is invisible to `catalog`'s
/// `every_shipped_machine_resumes_from_its_own_snapshot` for one reason: that
/// test's span is 2 ms and the NTSC frame counter's first IRQ is about 16.7 ms
/// in, so `irq_out` is `false` at the instant it snapshots and a lost `false`
/// is not a lost anything. This file's twenty milliseconds is past the first
/// assertion, and nothing in the fixture cartridge reads `$4015` to clear it.
/// The fix is a `write_bool`/`read_bool` pair in `src/dev/apu/mod.rs` with the
/// class-version bump and migration step that go with it, which belongs to
/// whoever owns that device.
const KNOWN_FAILURES: &[(&str, &str)] = &[
    // Empty, and it has already earned its keep once. `nes-ntsc` was here
    // because `apu.nes` did not save `Core::irq_out`, so a pending frame
    // interrupt was lost across a restore; the entry was written in one
    // worktree while the fix landed in another, and the "now passes: delete the
    // entry" arm below is what noticed. Keep that arm: an entry nobody removes
    // is a defect the tree has stopped looking for.
];

/// Split failures into the ones a ledger entry accounts for and the ones it
/// does not, and complain about entries that no longer fail.
fn against_the_ledger(failures: &[(&str, String)]) -> Vec<String> {
    let mut out = Vec::new();
    for (board, detail) in failures {
        if !KNOWN_FAILURES.iter().any(|(name, _)| name == board) {
            out.push(format!("`{board}`: {detail}"));
        }
    }
    for (board, why) in KNOWN_FAILURES {
        if !failures.iter().any(|(name, _)| name == board) {
            out.push(format!(
                "`{board}` is in KNOWN_FAILURES ({why}) and now passes: delete \
                 the entry"
            ));
        }
    }
    out
}

/// Build `board`, reset and not yet run.
fn build(board: &Board) -> Machine {
    let media = (board.media)();
    let mut options = catalog::build_options().expect("the catalog agrees with itself");
    for (slot, bytes) in &media {
        options.realize.media.insert(*slot, bytes.as_slice());
    }
    options.resolve.params.extend(
        board
            .params
            .iter()
            .map(|(k, v)| ((*k).to_string(), (*v).to_string())),
    );
    let entry = catalog::machine(board.name)
        .unwrap_or_else(|| panic!("`{}` is not in this build's catalog", board.name));
    let registry = catalog::registry().expect("a registry");
    rsemu::machine::build(entry.name, entry.source, &registry, &options)
        .unwrap_or_else(|e| panic!("`{}` realizes: {e}", board.name))
}

/// Run a fresh board to [`SPAN_A`], then on to `SPAN_A + SPAN_B`, saving at
/// both instants.
fn produce(board: &Board) -> (Vec<u8>, Vec<u8>) {
    let mut machine = build(board);
    machine.run_for(SPAN_A).expect("the board runs");
    let at = machine.save().expect("it snapshots");
    machine.run_for(SPAN_B).expect("it keeps running");
    let after = machine.save().expect("it snapshots again");
    (at, after)
}

/// The directory named by `var`, if it is set to something non-empty.
fn dir(var: &str) -> Option<PathBuf> {
    match env::var(var) {
        Ok(path) if !path.is_empty() => Some(PathBuf::from(path)),
        _ => None,
    }
}

fn read(dir: &Path, name: &str) -> Vec<u8> {
    let path = dir.join(name);
    fs::read(&path).unwrap_or_else(|e| {
        panic!(
            "{READ_DIR} names {}, and {} is not readable: {e} — did the writing \
             host run with a different feature set?",
            dir.display(),
            path.display()
        )
    })
}

/// The pair under test for `board`: read from the foreign host's files when
/// [`READ_DIR`] is set, produced here when it is not.
fn artefacts(board: &Board) -> (Vec<u8>, Vec<u8>) {
    match dir(READ_DIR) {
        Some(d) => (
            read(&d, &format!("{}.at", board.name)),
            read(&d, &format!("{}.after", board.name)),
        ),
        None => produce(board),
    }
}

/// Write every board's artefacts for another host to read. A no-op unless
/// [`WRITE_DIR`] is set, which is what makes this file harmless in an ordinary
/// run.
///
/// It is a `#[test]` rather than a binary because the whole point is that the
/// *same source* runs on both hosts: a separate writer binary could drift from
/// the reader, and the comparison would then be between two programs rather
/// than between two hosts.
#[test]
fn writes_the_artefacts_when_asked() {
    let Some(d) = dir(WRITE_DIR) else {
        return;
    };
    fs::create_dir_all(&d).expect("the writer's directory is creatable");
    for board in boards() {
        let (at, after) = produce(&board);
        fs::write(d.join(format!("{}.at", board.name)), &at).expect("the snapshot is writable");
        fs::write(d.join(format!("{}.after", board.name)), &after)
            .expect("the continuation is writable");
    }
}

/// Every snapshot is of a machine that has actually run.
///
/// Without this the test below could pass on a board that never executed an
/// instruction: two reset machines agree about everything, and a cross-host
/// comparison of two empty runs proves nothing at all. It is the same guard
/// `record_replay`'s `typing_at_the_machine_changes_where_it_ends_up` is.
#[test]
fn the_snapshots_are_of_machines_that_ran() {
    let mut report: Vec<String> = Vec::new();
    for board in boards() {
        let (at, after) = artefacts(&board);
        let fresh = build(&board).save().expect("a reset board snapshots");
        if at == fresh {
            report.push(format!(
                "`{}`: the artefact is a reset board, so nothing downstream of \
                 it means anything",
                board.name
            ));
        }
        if at == after {
            report.push(format!(
                "`{}`: the machine did not move over SPAN_B",
                board.name
            ));
        }
    }
    assert!(report.is_empty(), "{}", report.join("\n"));
}

/// A snapshot loads into a board that has only ever been reset, and the
/// restored machine then runs forward to the bytes the *writing* machine
/// reached.
///
/// The second comparison is the one that can see a field `save` omits; the
/// first is still a function of what `save` writes.
#[test]
fn a_snapshot_loads_into_a_reset_board_and_runs_forward_to_the_same_bytes() {
    let mut failures: Vec<(&str, String)> = Vec::new();
    for board in boards() {
        let (at, after) = artefacts(&board);

        let mut b = build(&board);
        if let Err(e) = b.load(&at) {
            failures.push((board.name, format!("the snapshot does not load: {e}")));
            continue;
        }
        let resaved = b.save().expect("it re-snapshots");
        if resaved != at {
            failures.push((
                board.name,
                format!(
                    "re-saving what was just loaded is not byte-identical: the \
                     format has more than one encoding for a state, or a chunk \
                     did not round-trip — {}",
                    differing_chunks(&resaved, &at).join("; ")
                ),
            ));
            continue;
        }
        if b.now() != SPAN_A {
            failures.push((
                board.name,
                format!("the restore did not carry the clock: {:?}", b.now()),
            ));
        }

        b.run_for(SPAN_B).expect("the restored board runs");
        let ran = b.save().expect("it snapshots");
        if ran != after {
            failures.push((
                board.name,
                format!(
                    "the restored machine diverged from the one the snapshot \
                     came from — some state `save` does not write is \
                     different, which is exactly what a byte comparison of the \
                     snapshot itself cannot see — {}",
                    differing_chunks(&ran, &after).join("; ")
                ),
            ));
        }
    }
    let unexpected = against_the_ledger(&failures);
    assert!(unexpected.is_empty(), "{}", unexpected.join("\n"));
}

/// A snapshot written on another host is byte-for-byte the one this host
/// writes.
///
/// This is the cross-host claim, and it only says anything when [`READ_DIR`]
/// points at a foreign host's files — with it unset the two sides are the same
/// bytes by construction, and the test declines to assert a tautology.
///
/// Byte identity is stronger than "loads correctly", and it is the property the
/// format promises: `core::state` writes little-endian fixed-width integers on
/// every host and sorts every collection, so a 32-bit `usize`, a different
/// pointer width and a different code generator must all produce the same file.
/// A difference here names the chunk that is carrying something of the host's
/// in it.
#[test]
fn a_foreign_snapshot_is_byte_identical_to_this_hosts_own() {
    let Some(d) = dir(READ_DIR) else {
        return;
    };
    let mut report: Vec<String> = Vec::new();
    for board in boards() {
        let foreign_at = read(&d, &format!("{}.at", board.name));
        let foreign_after = read(&d, &format!("{}.after", board.name));
        let (local_at, local_after) = produce(&board);

        if foreign_at != local_at {
            report.push(format!(
                "`{}`: the foreign snapshot is {} bytes against this host's {} \
                 — {}",
                board.name,
                foreign_at.len(),
                local_at.len(),
                differing_chunks(&foreign_at, &local_at).join("; ")
            ));
        } else if foreign_after != local_after {
            report.push(format!(
                "`{}`: the two hosts agree at the snapshot instant and disagree \
                 after running on, so the divergence is in execution rather \
                 than in the format — {}",
                board.name,
                differing_chunks(&foreign_after, &local_after).join("; ")
            ));
        }
    }
    assert!(report.is_empty(), "{}", report.join("\n"));
}

/// Where two byte strings first differ, for an error message that says
/// something: `assert_eq!` on two multi-kilobyte `Vec<u8>`s prints both.
fn first_difference(a: &[u8], b: &[u8]) -> Option<usize> {
    match a.iter().zip(b).position(|(x, y)| x != y) {
        Some(at) => Some(at),
        None if a.len() != b.len() => Some(a.len().min(b.len())),
        None => None,
    }
}

/// Which chunks two snapshots of the same machine disagree about.
///
/// An offset into the whole file names nothing a person can act on; a chunk
/// names the device. Same shape as `catalog`'s helper of the same name, and
/// for the same reason.
fn differing_chunks(a: &[u8], b: &[u8]) -> Vec<String> {
    use rsemu::core::state::StateReader;
    let (Ok(ra), Ok(rb)) = (StateReader::new(a), StateReader::new(b)) else {
        return vec![String::from("one of the two is not a snapshot at all")];
    };
    let mut out = Vec::new();
    for info in ra.chunks() {
        let (_, _, da) = ra.load_raw(info.path).expect("a listed chunk");
        let Ok((_, _, db)) = rb.load_raw(info.path) else {
            out.push(format!("{} missing", info.path));
            continue;
        };
        if da != db {
            out.push(format!(
                "{} [{}] {}/{} bytes, differ from offset {:?}",
                info.path,
                info.class,
                da.len(),
                db.len(),
                first_difference(da, db)
            ));
        }
    }
    out
}

/// No board on the list writes a host path into its snapshot.
///
/// A path is the one thing in a save state that cannot cross a host boundary:
/// it is not a property of the guest, it names a file on the machine that took
/// the snapshot, and no amount of little-endian discipline makes it portable.
/// A drive whose medium is snapshotted *by reference* writes exactly that —
/// `format <canonical host path> <capacity>`, `dev::blk::Image::open` — so this
/// test is the ledger entry for which boards can migrate and which cannot. It
/// is expected to fail the day a board here gets a referenced drive, and that
/// failure is the finding rather than a defect in the test.
///
/// `env::current_dir` is not a thing every host has — a `wasm32-wasip1` guest
/// with no preopened working directory errors — so the audit uses whatever host
/// strings it can get hold of and says nothing when it can get none.
#[test]
fn a_snapshot_carries_no_host_path() {
    let mut candidates: Vec<PathBuf> = Vec::new();
    if let Ok(cwd) = env::current_dir() {
        candidates.push(cwd);
    }
    for var in [WRITE_DIR, READ_DIR] {
        candidates.extend(dir(var));
    }
    // A root directory is not a host path for this purpose: under WASI the
    // working directory is `/`, and every instance path in the shape starts
    // with one. Only a directory with a parent names anything.
    candidates.retain(|p| p.parent().is_some_and(|parent| parent != Path::new("")));

    let mut report: Vec<String> = Vec::new();
    for board in boards() {
        let (at, _) = artefacts(&board);
        for candidate in candidates.iter().map(|p| p.to_string_lossy()) {
            if contains(&at, candidate.as_bytes()) {
                report.push(format!(
                    "`{}`: the snapshot contains the host path `{candidate}`, so \
                     it cannot be loaded anywhere else",
                    board.name
                ));
            }
        }
    }
    assert!(report.is_empty(), "{}", report.join("\n"));
}

/// Whether `haystack` contains `needle`. `[u8]::windows` panics on a zero
/// length, and an empty needle is in everything anyway.
fn contains(haystack: &[u8], needle: &[u8]) -> bool {
    !needle.is_empty()
        && haystack.len() >= needle.len()
        && haystack.windows(needle.len()).any(|w| w == needle)
}

/// A board that gains a device refuses every save state taken before it, and
/// says which device.
///
/// This is the empirical half of the argument in `core::state`'s
/// "The shape has no migration, and should not": a
/// [`MachineShape`](rsemu::core::state::MachineShape) is device classes at
/// instance paths plus region layout, it has no migration mechanism, and adding
/// one device to a board orphans every old snapshot of it however complete the
/// class-version table is. Boards change more often than chunk encodings do, so
/// this is the constraint that actually binds a save state in the wild — and
/// nothing in the tree pinned the behaviour until now, only `ShapeDiff`'s own
/// unit tests inside `core::state`.
///
/// The old build is synthesised by *removing* a device from a snapshot's shape
/// and its chunk with it, which is exactly the file a build without that device
/// would have written: the format has one encoding per state, so there is
/// nothing to guess. That is the same trick `tests/snapshot_migration.rs` plays
/// for a class version, and it works for the same reason.
///
/// What is asserted is not merely that it fails. It fails with a **diff naming
/// the device** — §4.5 promises a diff rather than a boolean, and a refusal
/// nobody can read is what sends a user to a forum instead of to their old
/// build.
#[test]
fn a_board_that_gained_a_device_refuses_its_older_save_states() {
    use rsemu::core::state::{MachineShape, StateReader, StateWriter};

    for board in boards() {
        let (at, _) = artefacts(&board);
        let reader = StateReader::new(&at).expect("a snapshot");

        // The last device in path order, which is an arbitrary one and the
        // point is that any of them will do.
        let (dropped, _) = reader
            .shape()
            .devices()
            .iter()
            .next_back()
            .expect("every board has a device");
        let dropped = dropped.clone();

        let mut older = MachineShape::new();
        for (path, class) in reader.shape().devices() {
            if path != &dropped {
                older.add_device(path, class).expect("paths are unique");
            }
        }
        for region in reader.shape().regions() {
            older.add_region(&region.space, &region.name, region.base, region.size);
        }

        let mut w = StateWriter::new(older);
        for info in reader.chunks() {
            if info.path == dropped {
                continue;
            }
            let (class, version, data) = reader.load_raw(info.path).expect("a listed chunk");
            w.raw_chunk(info.path, class, version, data)
                .expect("chunks stay in key order");
        }
        let older = w.to_vec().expect("it encodes");

        let error = build(&board)
            .load(&older)
            .expect_err("a board with a device the snapshot never had must refuse");
        let message = error.to_string();
        assert!(
            message.contains(&dropped),
            "`{}`: the refusal does not name `{dropped}`, so the user cannot \
             tell what changed: {message}",
            board.name
        );
    }
}
